/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_leaf_flashlightcontrol_FlashLightControlActivity */

#ifndef _Included_com_leaf_flashlightcontrol_FlashLightControlActivity
#define _Included_com_leaf_flashlightcontrol_FlashLightControlActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_leaf_flashlightcontrol_FlashLightControlActivity
 * Method:    fltNativeInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_leaf_flashlightcontrol_FlashLightControlActivity_fltNativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_leaf_flashlightcontrol_FlashLightControlActivity
 * Method:    fltNativeDeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_leaf_flashlightcontrol_FlashLightControlActivity_fltNativeDeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_leaf_flashlightcontrol_FlashLightControlActivity
 * Method:    fltNativeSelectDevice
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_leaf_flashlightcontrol_FlashLightControlActivity_fltNativeSelectDevice
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_leaf_flashlightcontrol_FlashLightControlActivity
 * Method:    fltNativeSetDuty
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_leaf_flashlightcontrol_FlashLightControlActivity_fltNativeSetDuty
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_leaf_flashlightcontrol_FlashLightControlActivity
 * Method:    fltNativeOnOff
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_leaf_flashlightcontrol_FlashLightControlActivity_fltNativeOnOff
  (JNIEnv *, jobject, jint);

JNIEXPORT jint JNICALL Java_com_leaf_flashlightcontrol_FlashLightControlActivity_fltNativeTimeout
  (JNIEnv *env, jobject object, jint);
#ifdef __cplusplus
}
#endif
#endif
